### PR TITLE
Use jpg for splash to reduce size

### LINKED ISSUE #80: splash_background.png is not optimized and may not be the right format
The `splash_background.png` image has not been optimized &mdash; it is over 113KB+ 
Changing the format of the image may help too (from `.png` to `.jpg`) because of all the gradients it contains.

### PR DESCRIPTION
**Pull request by redonkulus**
@jedireza @Vijar 

Fixes #80

This reduces the size from 113kb to 17kb! The quality looks good on my screen, but this is on my retina mac.

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by jedireza** [comment]
Let's do it! :rocket:

**Comment by lingyan** [comment]
:100:

**Comment by redonkulus** [comment]
OK used @thierryk image and saved an additional 5kb.

**Pull request merged**
