### PR TITLE
:bug: implement the sticky footer trick. 

### PR DESCRIPTION
**Pull request by koulmomo**
@mridgway @Vijar 
see: http://ryanfait.com/sticky-footer/ for more info

### CODE REVIEW

**Comment by Vijar** [comment]
Looks fine to me

**Comment by mridgway** [comment]
Why?

**Comment by jedireza** [comment]
I don't think we need this. But if we were to keep it, it doesn't need to be it's own file, it could be added to the other footer styles.

**Comment by redonkulus** [comment]
Seems like a non-issue, as all pages have content that stretches past the left navigation. Thanks for the PR though :)

**Pull request closed without merging**
