### PR TITLE
add fluxible logo and use new font

### PR DESCRIPTION
**Pull request by redonkulus**
@annawchou @jedireza @mridgway @lingyan 

I've changed from using Nobile custom font to Montserrat as suggested by @annawchou.

Check out the screen shots below:

screen shot 2015-04-30 at 6 01 10 am

screen shot 2015-04-30 at 6 01 18 am

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by jedireza** [comment]
I think SVG files are vector and can be resized without loss. Do we need two (large/small)?

**Comment by thierryk** [comment]
@jedireza you're right, no need for 2 versions. But why `svg` in the first place? `png` is better supported. On acss.io we are using a PNG and we re-use that same image (that we resize) inside the header on other pages.

**Comment by redonkulus** [comment]
@annawchou suggested the small one because when the larger logo was resized to the smaller one, it was too hard to read. I didn't actually try this myself, I just used the smaller one instead. Anna can comment.

**Comment by annawchou** [comment]
@thierryk when the logo is resized the detail of the spacing gets lost

**Comment by annawchou** [comment]
@redonkulus can you add a `line-height` to vertically align the logo in the top nav?

**Comment by annawchou** [comment]
@redonkulus delete logo_big and just use the logo_small and resize that one for the splash page

**Comment by thierryk** [comment]
@redonkulus yes, if you use SVG, it is better to use the small one, but with PNG you can start big and resize it. Better browser support

**Comment by redonkulus** [comment]
@thierryk @jedireza using the small one now, removed the large one.

**Pull request merged**
