### PR TITLE
apply react-i13n for instrumentation

### PR DESCRIPTION
**Pull request by kaesonho**
created `react-i13n-ga`
https://github.com/kaesonho/react-i13n-ga
https://www.npmjs.com/package/react-i13n-ga

apply `react-i13n` and 
1. send out pageview beacon 
2. send out click beacon(event beacon https://developers.google.com/analytics/devguides/collection/analyticsjs/events). 
pv works as usual and we can see the event report for clicks in google analytics. 

@redonkulus @mridgway @lingyan @Vijar

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by kaesonho** [comment]
build failed because we haven't get `react-i13n` published

**Comment by kaesonho** [comment]
the react-i13n pkg is generated and fixed the conflicts. Please check

we will see following error for npm install due to the old version npm
```
webdriver/node_modules/ws/node_modules/bufferutil/build'
npm ERR! peerinvalid The package react does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer fluxible@0.4.10 wants react@0.13.x
npm ERR! peerinvalid Peer fluxible-router@0.1.7 wants react@0.13.x
npm ERR! peerinvalid Peer react-i13n@0.1.10 wants react@<= 0.13.x
```
so as we discussed today, add `node10` into allow failures setting in `.travis.yml`, 
do we need to disable that directly or add some note?

**Comment by redonkulus** [comment]
@kaesonho please add a note in the README that nodejs10 users will not be able to install the dependencies due to this issue.

**Comment by kaesonho** [comment]
sure thanks, I think it's due to old npm version, let me find some detail and add it into README

**Comment by kaesonho** [comment]
updated, with react-i13n@0.1.11 which set peerDependencies as `"react": "<0.14.0"`, we should able to get node10 passed, please check

**Comment by redonkulus** [comment]
:+1:

**Pull request merged**
