### PR TITLE
Fixing a typo in Quick Start + a few other tweaks

### PR DESCRIPTION
**Pull request by LouisStAmour**
Just a suggestion. That "wan't" really bugged me. :D

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by LouisStAmour** [comment]
Line 15 could also have used a semi-colon instead of the word changes I suggested. I'm probably overthinking this one. :)

**Comment by redonkulus** [comment]
looks good to me. thanks :)

**Pull request merged**
