### PR TITLE
changed nav styles, links, footer, buttons

### PR DESCRIPTION
**Pull request by kaiiu**
- added active state classes for links (someone else needs to actually implement the states)
- button style for front page
- changed footer styles

### CODE REVIEW

**Comment by jedireza** [comment]
Screen shot?

**Comment by kaiiu** [comment]
hover state:
screen shot 2015-01-27 at 1 55 45 pm
screen shot 2015-01-27 at 1 55 29 pm
screen shot 2015-01-27 at 1 55 35 pm

**Comment by jedireza** [comment]
What's the flickr logo for?

**Comment by kaiiu** [comment]
It's supposed to be part of the attribution

**Comment by redonkulus** [comment]
@kaiiu i think @jedireza means you added the flickr logo but do not use it in the page.

**Comment by redonkulus** [comment]
:shipit: i like the new splash button and footer styles.

**Comment by kaiiu** [comment]
@redonkulus i know, i don't know how to add the flickr logo :(

**Comment by mridgway** [comment]
I say we merge this to get it in and then add the logo later.

**Comment by redonkulus** [comment]
Sure

**Pull request merged**
