### PR TITLE
Migrate css to atomic css 3

### PR DESCRIPTION
**Pull request by redonkulus**
@mridgway @renatoi @Vijar

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by Vijar** [comment]
:shipit:

**Comment by Vijar** [comment]
It doesn't look too happy when I tried to run it locally

screen shot 2015-05-30 at 4 19 25 pm

**Comment by Vijar** [comment]
Nevermind, its fine after installing latest `grunt-atomizer`.

:ship:

**Comment by renatoi** [comment]
:+1:

**Pull request merged**
