### PR TITLE
[WIP] migrate to es6

### PR DESCRIPTION
**Pull request by redonkulus**
@mridgway @jedireza @Vijar 

I got most of the work done (including tests). However, I'm not able to convert the `Application` component to `React.Component` until https://github.com/yahoo/flux-router-component/pull/81 is merged, so I can use the route handler and remove the RouterMixin.

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by jedireza** [comment]
This is looking good.

We talked about creating a thin shim for `/server.js` so the majority of that code can be converted to es6.

I'd also like to remove the `'use strict';` lines.

Also, while we're moving things to es6 I'd like to revisit two specific coding conventions. One being that `require`/`import` statements always be at the top of a file. We're typically good at this, I don't see it often.

The second convention I'd like to address is more generous line spacing so code is more comfortable to read. For example, here is the `/stores/ApplicationStore.js` file as I'd like to see it.

```js
import {BaseStore} from 'fluxible/addons';
import routes from '../configs/routes';

class ApplicationStore extends BaseStore {
    constructor(dispatcher) {
        super(dispatcher);
        this.currentPageName = null;
        this.currentRoute = null;
        this.pageTitle = '';
    }

    changeRoute(route) {
        this.currentRoute = route;
        this.emitChange();
    }

    handleNavigate(route) {
        this.currentPageName = null;
        this.emitChange();
    }

    updatePageTitle(title) {
        this.pageTitle = title.pageTitle;
        this.emitChange();
    }

    status500() {
        this.currentPageName = '500';
        this.emitChange();
    }

    status404() {
        this.currentPageName = '404';
        this.emitChange();
    }

    getCurrentPageName() {
        return this.currentPageName;
    }

    getPageTitle() {
        return this.pageTitle;
    }

    getCurrentRoute() {
        return this.currentRoute;
    }

    dehydrate() {
        if (this.currentRoute) {
            delete this.currentRoute.config;
        }

        return {
            currentPageName: this.currentPageName,
            route: this.currentRoute,
            pageTitle: this.pageTitle
        };
    }

    rehydrate(state) {
        this.currentPageName = state.currentPageName;
        this.currentRoute = state.route;

        if (state.route) {
            this.currentRoute.config = routes[this.currentRoute.name];
        }

        this.pageTitle = state.pageTitle;
    }
}

ApplicationStore.storeName = 'ApplicationStore';

ApplicationStore.handlers = {
    'CHANGE_ROUTE_START': 'changeRoute',
    'CHANGE_ROUTE_SUCCESS': 'handleNavigate',
    'UPDATE_PAGE_TITLE': 'updatePageTitle',
    'STATUS_500': 'status500',
    'STATUS_404': 'status404'
};

export default ApplicationStore;
```

**Comment by redonkulus** [comment]
@jedireza I've updated the spacing and migrated server.js to use es6. i created a `start.js` file registers that babel and then includes server.js.

**Comment by jedireza** [comment]
:+1:

**Comment by redonkulus** [comment]
Merged this to master locally.

**Pull request closed without merging**
