### PR TITLE
update guide to reflect current dispatcher.js code

### PR DESCRIPTION
**Pull request by joshuapurcell**
Old guide had dispatcher.js code that pointed to a previous dependency (flux). Updated to reflect the current code.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by redonkulus** [comment]
Thanks!

**Comment by mridgway** [comment]
Hmm, this article was actually taking a `flux` example and make it `fluxible`. So it was actually meant to have `flux` as the dependency. I think this should be reverted.

**Comment by joshuapurcell** [comment]
Yep I understand. It seemed weird going through the guide the first time around that a new dependency was being brought in ('flux'). In further sections you do have the current source included though, so as long people aren't expecting to create the project as they go the guide (which is what I was trying to do) it works as it is. Great article by the way!

**Pull request merged**
